# Generated by Django 4.0.7 on 2022-08-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0002_alter_forgreeting_pictureimg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForGreeting',
            new_name='Greeting',
        ),
    ]
