# Generated by Django 4.0.7 on 2022-08-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0004_listofmetro_metroshortinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListOfMetro',
        ),
    ]
