# Generated by Django 4.0.7 on 2022-08-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0005_delete_listofmetro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metroshortinfo',
            name='info',
            field=models.TextField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='metroshortinfo',
            name='openDate',
            field=models.DateField(),
        ),
    ]
