# Generated by Django 4.0.7 on 2022-09-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0006_alter_metroshortinfo_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metroshortinfo',
            old_name='info',
            new_name='commonInfo',
        ),
        migrations.AddField(
            model_name='metroshortinfo',
            name='hacks_facts',
            field=models.TextField(default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='metroshortinfo',
            name='history',
            field=models.TextField(default='', max_length=1200),
        ),
    ]
