# Generated by Django 4.0.7 on 2022-09-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0007_rename_info_metroshortinfo_commoninfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('valute', models.TextField(max_length=15)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='logomeaning')),
            ],
        ),
    ]
