# Generated by Django 4.0.7 on 2022-09-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0008_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='info',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
