# Generated by Django 4.0.7 on 2022-09-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0009_ticket_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ages',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
