# Generated by Django 4.0.7 on 2022-09-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0010_ticket_ages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='valute',
            field=models.TextField(max_length=50),
        ),
    ]
