# Generated by Django 4.0.7 on 2022-09-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0011_alter_ticket_valute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ages',
            field=models.CharField(blank=True, choices=[('Grown-ups', '18 - 60 years'), ('Students', '18 - 26 years'), ('Seniors', '60 - 65 years'), ('ElderTeens', '15 - 18 years')], default='Grown-ups', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Hourly', 'Hourly')], default='Daily', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='valute',
            field=models.TextField(choices=[('czech krone', 'Czech Koruna, KCZ')], default='czech krone', max_length=50),
        ),
    ]
