# Generated by Django 4.0.7 on 2022-09-06 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0012_alter_ticket_ages_alter_ticket_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetroInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofiname', models.CharField(max_length=100)),
                ('popname', models.CharField(blank=True, max_length=150, null=True)),
                ('locat', models.CharField(max_length=30)),
                ('org', models.CharField(max_length=150)),
                ('start', models.DateField()),
                ('works', models.TextField(max_length=120)),
                ('viewinf', models.CharField(max_length=125)),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='logomeaning/')),
                ('intro', models.TextField(max_length=1200)),
                ('HistorY', models.TextField(max_length=2400)),
                ('facts', models.TextField(blank=True, max_length=1200, null=True)),
                ('tickets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseInfo.ticket')),
            ],
        ),
    ]
