# Generated by Django 4.0.7 on 2022-09-06 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0013_metroinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metroinfo',
            name='tickets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseInfo.ticket'),
        ),
    ]
