# Generated by Django 4.0.7 on 2022-09-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0014_alter_metroinfo_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metroinfo',
            name='tickets',
        ),
    ]
