# Generated by Django 4.0.7 on 2022-09-08 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0015_remove_metroinfo_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='metro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseInfo.metroinfo'),
        ),
    ]
