# Generated by Django 4.0.7 on 2022-09-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0019_alter_ticket_metro'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exchange_table')),
                ('country', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('currency', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=3)),
            ],
        ),
    ]
