# Generated by Django 4.0.7 on 2022-09-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0020_tabledata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabledata',
            name='price',
        ),
    ]
