# Generated by Django 4.0.7 on 2022-09-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0021_remove_tabledata_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
