# Generated by Django 4.0.7 on 2022-09-13 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0023_alter_ticket_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metroinfo',
            name='facts',
        ),
        migrations.CreateModel(
            name='FactsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('image', models.ImageField(upload_to='facts_table')),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('metro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facts', to='baseInfo.metroinfo')),
            ],
        ),
    ]
