# Generated by Django 4.0.7 on 2022-09-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0024_remove_metroinfo_facts_factsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='metroshortinfo',
            name='opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metroshortinfo',
            name='city',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='metroshortinfo',
            name='hacks_facts',
            field=models.TextField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='metroshortinfo',
            name='history',
            field=models.TextField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='metroshortinfo',
            name='n_ofiName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='metroshortinfo',
            name='server',
            field=models.TextField(max_length=150),
        ),
    ]
