# Generated by Django 4.0.7 on 2022-09-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0025_metroshortinfo_opened_alter_metroshortinfo_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metroshortinfo',
            name='commonInfo',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='metroshortinfo',
            name='hacks_facts',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='metroshortinfo',
            name='history',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='metroshortinfo',
            name='workTime',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
